package com.automation.reports;

import com.automation.utils.PropertyReader;
import com.automation.utils.TestResultTracker;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import jakarta.activation.DataHandler;
import jakarta.activation.DataSource;
import jakarta.activation.FileDataSource;
import jakarta.mail.*;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeBodyPart;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.internet.MimeMultipart;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.Properties;

/**
 * Sends the Extent HTML report as an email attachment after all tests finish.
 * Configuration is read from config.properties (email.* keys).
 */
public class EmailReporter {

    private static final Logger logger = LogManager.getLogger(EmailReporter.class);

    private EmailReporter() {}

    /**
     * Send test result email with the given Extent report file attached.
     *
     * @param reportFilePath absolute path to the generated Extent HTML report
     * @param passed         number of passed scenarios
     * @param failed         number of failed scenarios
     */
    public static void sendReport(String reportFilePath, int passed, int failed) {
        try {
            PropertyReader.loadConfigProperties();

            String enabled = PropertyReader.getConfigProperty("email.enabled");
            if (!"true".equalsIgnoreCase(enabled)) {
                logger.info("Email reporting disabled (email.enabled=false)");
                return;
            }

            String smtpHost    = PropertyReader.getConfigProperty("email.smtp.host");
            String smtpPort    = PropertyReader.getConfigProperty("email.smtp.port");
            String smtpUser    = PropertyReader.getConfigProperty("email.smtp.username");
            String smtpPass    = PropertyReader.getConfigProperty("email.smtp.password");
            String fromAddr    = PropertyReader.getConfigProperty("email.from");
            String fromName    = PropertyReader.getConfigProperty("email.from.name");
            String toAddr      = PropertyReader.getConfigProperty("email.to");
            String platform    = PropertyReader.getPlatform();

            if (smtpHost == null || smtpHost.isBlank() || toAddr == null || toAddr.isBlank()) {
                logger.warn("Email config incomplete — skipping email report. Set email.smtp.host and email.to in config.properties");
                return;
            }

            String dateStr = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss").format(new Date());
            String subject = "OneApp Mobile Automation Report | %s | %s | %d Passed / %d Failed".formatted(
                platform.toUpperCase(), dateStr, passed, failed);

            int total = passed + failed;
            String passRate = total > 0 ? "%.0f%%".formatted((passed * 100.0 / total)) : "N/A";
            String statusColor = failed > 0 ? "#dc3545" : "#28a745";
            String statusLabel = failed > 0 ? "FAILED" : "PASSED";

            // Build HTML email body
            String htmlBody = "<!DOCTYPE html><html><body style='font-family:Arial,sans-serif;'>"
                    + "<table width='100%' cellpadding='0' cellspacing='0'>"
                    + "<tr><td style='background:" + statusColor + ";padding:18px 24px;'>"
                    + "<h2 style='color:#fff;margin:0;'>Automation Test Report — " + statusLabel + "</h2>"
                    + "</td></tr></table>"
                    + "<br>"
                    + "<table border='1' cellpadding='10' cellspacing='0' "
                    +       "style='border-collapse:collapse;width:60%;min-width:340px;'>"
                    + "<tr style='background:#f2f2f2;'><th align='left'>Metric</th><th align='left'>Value</th></tr>"
                    + "<tr><td>Execution Date</td><td>" + dateStr + "</td></tr>"
                    + "<tr><td>Platform</td><td>" + platform.toUpperCase() + "</td></tr>"
                    + "<tr><td>Total Scenarios</td><td>" + total + "</td></tr>"
                    + "<tr><td><span style='color:#28a745;font-weight:bold;'>✓ Passed</span></td>"
                    +       "<td style='color:#28a745;font-weight:bold;'>" + passed + "</td></tr>"
                    + "<tr><td><span style='color:#dc3545;font-weight:bold;'>✗ Failed</span></td>"
                    +       "<td style='color:#dc3545;font-weight:bold;'>" + failed + "</td></tr>"
                    + "<tr><td>Pass Rate</td><td><b>" + passRate + "</b></td></tr>"
                    + "</table>"
                    + "<br>"
                    + buildFeatureTable()
                    + "<br>"
                    + "<p>The full Extent HTML report is attached to this email.</p>"
                    + "<p style='color:#888;font-size:12px;'>Generated by OneApp Automation Framework</p>"
                    + "</body></html>";

            // Configure SMTP
            Properties props = new Properties();
            props.put("mail.smtp.host",                smtpHost);
            props.put("mail.smtp.port",                smtpPort);
            props.put("mail.smtp.auth",                "true");
            props.put("mail.smtp.starttls.enable",     "true");
            props.put("mail.smtp.ssl.trust",           smtpHost);
            props.put("mail.smtp.connectiontimeout",   "10000");
            props.put("mail.smtp.timeout",             "10000");

            Session session = Session.getInstance(props, new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(smtpUser, smtpPass);
                }
            });

            MimeMessage message = new MimeMessage(session);
            if (fromName != null && !fromName.isBlank()) {
                message.setFrom(new InternetAddress(fromAddr, fromName));
            } else {
                message.setFrom(new InternetAddress(fromAddr));
            }
            // Support comma-separated recipients
            for (String addr : toAddr.split(",")) {
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(addr.trim()));
            }
            message.setSubject(subject);

            // Multipart: HTML body + report attachment
            MimeMultipart multipart = new MimeMultipart();

            MimeBodyPart bodyPart = new MimeBodyPart();
            bodyPart.setContent(htmlBody, "text/html; charset=utf-8");
            multipart.addBodyPart(bodyPart);

            // Attach extent report if it exists
            if (reportFilePath != null) {
                File reportFile = new File(reportFilePath);
                if (reportFile.exists()) {
                    MimeBodyPart attachPart = new MimeBodyPart();
                    DataSource ds = new FileDataSource(reportFile);
                    attachPart.setDataHandler(new DataHandler(ds));
                    attachPart.setFileName(reportFile.getName());
                    multipart.addBodyPart(attachPart);
                } else {
                    logger.warn("Report file not found for email attachment: " + reportFilePath);
                }
            }

            message.setContent(multipart);
            Transport.send(message);

            logger.info("Test report email sent to: " + toAddr);
            System.out.println("\u001B[36m✉  Report email sent to: " + toAddr + "\u001B[0m");

        } catch (Exception e) {
            logger.error("Failed to send test report email: " + e.getMessage(), e);
            System.out.println("\u001B[33m⚠  Email report skipped: " + e.getMessage() + "\u001B[0m");
        }
    }

    /**
     * Builds an HTML table with per-feature pass/fail breakdown from TestResultTracker.
     */
    private static String buildFeatureTable() {
        Map<String, int[]> stats = TestResultTracker.getFeatureStats();
        if (stats.isEmpty()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("<h3 style='margin-bottom:6px;'>Feature-wise Breakdown</h3>");
        sb.append("<table border='1' cellpadding='10' cellspacing='0' ")
          .append("style='border-collapse:collapse;width:60%;min-width:340px;'>")
          .append("<tr style='background:#f2f2f2;'>")
          .append("<th align='left'>Feature</th>")
          .append("<th align='left'>Total</th>")
          .append("<th align='left'>✓ Passed</th>")
          .append("<th align='left'>✗ Failed</th>")
          .append("<th align='left'>Pass Rate</th>")
          .append("<th align='left'>Status</th>")
          .append("</tr>");

        for (Map.Entry<String, int[]> entry : stats.entrySet()) {
            String feature   = entry.getKey();
            int fp           = entry.getValue()[0];
            int ff           = entry.getValue()[1];
            int ft           = fp + ff;
            String rate      = ft > 0 ? "%.0f%%".formatted((fp * 100.0 / ft)) : "N/A";
            String rowColor  = ff > 0 ? "#fff3f3" : "#f3fff3";
            String statusBadge = ff > 0
                ? "<span style='background:#dc3545;color:#fff;padding:2px 8px;border-radius:4px;font-size:12px;'>FAIL</span>"
                : "<span style='background:#28a745;color:#fff;padding:2px 8px;border-radius:4px;font-size:12px;'>PASS</span>";

            sb.append("<tr style='background:").append(rowColor).append(";'>")
              .append("<td><b>").append(feature).append("</b></td>")
              .append("<td>").append(ft).append("</td>")
              .append("<td style='color:#28a745;font-weight:bold;'>").append(fp).append("</td>")
              .append("<td style='color:#dc3545;font-weight:bold;'>").append(ff).append("</td>")
              .append("<td>").append(rate).append("</td>")
              .append("<td>").append(statusBadge).append("</td>")
              .append("</tr>");
        }
        sb.append("</table>");
        return sb.toString();
    }
}
